su_fkik:
  ros__parameters:
    End_Effector_Offset: [0.075, 0.0, 0.02]
    Simulation: true
    Inverse_Kinematics: true
    control_loop_hz: 1000.0
    numerical_calc_loop_hz: 50.0

trajectory_generator:
  ros__parameters:
    position_delta_cmd: [0.1, 0.1, 0.1, 0.1]  #버튼한번당 바뀌는 커맨드속도
    force_delta_cmd: 0.003
    control_loop_hz: 200.0
    numerical_calc_loop_hz: 50.0
    force_lpf_cof: 3
    normal_vector_estimator_lpf_cof: 3
