---
- logging_topic_name: "/cf2/pose"
  logging_type_name: "geometry_msgs::msg::PoseStamped"
- logging_topic_name: "/pen/EE_cmd_xyzYaw"
  logging_type_name: "std_msgs::msg::Float64MultiArray"
- logging_topic_name: "/turtle1/pose"
  logging_type_name: "turtlesim::msg::Pose"
- logging_topic_name: "/turtle1/cmd_vel"
  logging_type_name: "geometry_msgs::msg::Twist"  
  
